# Práctica 1

## 3) Probando codigo en python

In [22]:
import numpy as np

1 + 3
a = 7
b = a + 1
print ( "b = " , b)

b =  8


In [24]:
# Vectores
v = np.array ( [ 1 , 2 , 3 , -1 ] )
w = np.array ( [ 2 , 3 , 0 , 5 ] )
print ( "v + w = " , v + w)
print ( "2∗v = " , 2*v )
print ( "v∗∗2 = " , v **2)

v + w =  [3 5 3 4]
2∗v =  [ 2  4  6 -2]
v∗∗2 =  [1 4 9 1]


In [32]:
# Matrices (ejecutar los comandos uno a uno para ver los resultados)
A = np.array ( [ [ 1 , 2 , 3 , 4 , 5 ] , [ 0 , 1 , 2 , 3 , 4 ] , [ 2 , 3 , 4 , 5 , 6 ] , [ 0 , 0 , 1 , 2 , 3 ] , [ 0 , 0 , 0 , 0 , 1 ] ] )
print(A)

[[1 2 3 4 5]
 [0 1 2 3 4]
 [2 3 4 5 6]
 [0 0 1 2 3]
 [0 0 0 0 1]]


In [34]:
A[ 0 : 2 , 3 : 5 ]

array([[4, 5],
       [3, 4]])

In [36]:
A[ : 2 , 3 : ]

array([[4, 5],
       [3, 4]])

In [38]:
A[ [ 0 , 2 , 4 ] , : ]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [0, 0, 0, 0, 1]])

In [40]:
ind = np.array ( [ 0 , 2 , 4 ] )

In [42]:
A[ ind , ind ]

array([1, 4, 1])

In [44]:
A[ ind , ind [ : , None ] ]

array([[1, 2, 0],
       [3, 4, 0],
       [5, 6, 1]])

In [54]:
# Numeros complejos
1j *1j

(-1+0j)

In [1]:
(1+2j)*1j

(-2+1j)